### ISSUE TITLE
for other reference genomes?

### ISSUE THREAD

**Issue by jianshu93** [bioinfo-pf-curie/mpiBWA#49]
Hello mpiBWA team,

I hav this error when index my own genomes:
bwa index pico_all.fasta
mpiBWAIdx pico_all.fasta
[M::bwa_idx_load_from_disk] read 0 ALT contigs

The .map files is 0 in size.

what could be the problem?

Thanks,

Jianshu

**Comment by jianshu93** [comment]
There are cases where mapping reads to a lot of genomes, like bacterial genomes, total reference genome size could be even larger than hummer genome (pool all genomes).

This only works for human genome? I do not understand this part.

Thanks,

Jianshu

**Comment by fredjarlier** [comment]
Hi Juanshu, 
Thanks for reporting. To say truth I never tested other genomes except human.
I can try to reproduce the bug. What size is your bacterial genomes and how do you build it please?
best
frederic

**Comment by jianshu93** [comment]
the released source with configure fails on RHEL，the original github one finally works. Still the problem is using more than 5 processes will always fail.

**Comment by fredjarlier** [comment]
ok I will check the sources. 
it fails for both openMPI and MVAPICH?
