### ISSUE TITLE
parallel_aux.c:318: find_process_starting_offset_mt: Assertion `*p == '@'' failed.

### ISSUE THREAD

**Issue by apelin20** [bioinfo-pf-curie/mpiBWA#71]
Hello,

I have been getting the error shown in the log below. I have been trying to reduce the complexity of the task:
- only 16 threads
- smaller fasta (human mtDNA only)
- and finally, feeding reads as .fastq and not .fastq.gz

The last step seems to overcome the problem. Is fastq.gz not supported as input? I must be missing something. 

Thanks for your help. A

`##### Output for job 4246011:
rank 0: is multithread ok ? 1
all ranks will use 8 threads per mpi job 
main: shared memory is set to core 
main: controls are done. Start analyzing fastqs it could take few minutes...
main: shared memory is set to core 
mpiBWA: parallel_aux.c:318: find_process_starting_offset_mt: Assertion `*p == '@'' failed.
[qb3-id154:2931798] *** Process received signal ***
[qb3-id154:2931798] Signal: Aborted (6)
[qb3-id154:2931798] Signal code:  (-6)
[qb3-id154:2931798] [ 0] /lib64/libpthread.so.0(+0x12cf0)[0x145d8cdf0cf0]
[qb3-id154:2931798] [ 1] /lib64/libc.so.6(gsignal+0x10f)[0x145d8c160acf]
[qb3-id154:2931798] [ 2] /lib64/libc.so.6(abort+0x127)[0x145d8c133ea5]
[qb3-id154:2931798] [ 3] /lib64/libc.so.6(+0x21d79)[0x145d8c133d79]
[qb3-id154:2931798] [ 4] /lib64/libc.so.6(+0x47426)[0x145d8c159426]
[qb3-id154:2931798] [ 5] /wynton/home/krogan/apelin/programs/mpiBWA/local/bin/mpiBWA[0x42580d]
[qb3-id154:2931798] [ 6] /wynton/home/krogan/apelin/programs/mpiBWA/local/bin/mpiBWA[0x405dca]
[qb3-id154:2931798] [ 7] /lib64/libc.so.6(__libc_start_main+0xe5)[0x145d8c14cd85]
[qb3-id154:2931798] [ 8] /wynton/home/krogan/apelin/programs/mpiBWA/local/bin/mpiBWA[0x40cd6e]
[qb3-id154:2931798] *** End of error message ***
mpiBWA: parallel_aux.c:318: find_process_starting_offset_mt: Assertion `*p == '@'' failed.
[qb3-id210:3970400] *** Process received signal ***
[qb3-id210:3970400] Signal: Aborted (6)
[qb3-id210:3970400] Signal code:  (-6)
[qb3-id210:3970400] [ 0] /lib64/libpthread.so.0(+0x12cf0)[0x150e80687cf0]
[qb3-id210:3970400] [ 1] /lib64/libc.so.6(gsignal+0x10f)[0x150e7f9f7acf]
[qb3-id210:3970400] [ 2] /lib64/libc.so.6(abort+0x127)[0x150e7f9caea5]
[qb3-id210:3970400] [ 3] /lib64/libc.so.6(+0x21d79)[0x150e7f9cad79]
[qb3-id210:3970400] [ 4] /lib64/libc.so.6(+0x47426)[0x150e7f9f0426]
[qb3-id210:3970400] [ 5] /wynton/home/krogan/apelin/programs/mpiBWA/local/bin/mpiBWA[0x42580d]
[qb3-id210:3970400] [ 6] /wynton/home/krogan/apelin/programs/mpiBWA/local/bin/mpiBWA[0x405dca]
[qb3-id210:3970400] [ 7] /lib64/libc.so.6(__libc_start_main+0xe5)[0x150e7f9e3d85]
[qb3-id210:3970400] [ 8] /wynton/home/krogan/apelin/programs/mpiBWA/local/bin/mpiBWA[0x40cd6e]
[qb3-id210:3970400] *** End of error message ***
--------------------------------------------------------------------------
prterun noticed that process rank 0 with PID 3970400 on node qb3-id210 exited on
signal 6 (Aborted).
--------------------------------------------------------------------------
`

**Comment by fredjarlier** [comment]
Hi @apelin20 and happy new year... 

Indeed mpibwa don't accept gz file as input only fastq.
So far I leave parallel uncompression for specialized tools like pigz, pbzip2,...though it's taking more disk space generally it's faster. I notice  that the shared memory is set to core is it normal? what's the command line?

best

fred
